/**
 * Portfolio — Build Design System
 * =============================================================================
 * Runs inside Figma and builds the whole file natively: variable collections
 * with Light/Dark modes, text styles, component sets with real variants, and
 * screens assembled from instances with auto-layout.
 *
 * This is the same Plugin API work the Figma MCP server would do remotely —
 * run here instead because the Starter plan caps MCP at 20 calls a month.
 * Running locally has no quota.
 *
 * Generated by `npm run figma:plugin`. Edit src/ and rebuild; do not edit
 * code.js by hand.
 * =============================================================================
 */

const WARNINGS = [];
const warn = (msg) => { if (!WARNINGS.includes(msg)) WARNINGS.push(msg); };

// ---------------------------------------------------------------- colour ----
const hex = (h) => {
  const n = parseInt(h.slice(1), 16);
  return { r: ((n >> 16) & 255) / 255, g: ((n >> 8) & 255) / 255, b: (n & 255) / 255 };
};
const solid = (h, opacity) => {
  const p = { type: 'SOLID', color: hex(h) };
  if (opacity !== undefined) p.opacity = opacity;
  return p;
};

// ------------------------------------------------------------ variables -----
/** Bind a node's fill to a colour variable. */
function fillVar(node, variable) {
  if (!variable) { warn('fillVar called without a variable'); return; }
  const paint = figma.variables.setBoundVariableForPaint(
    { type: 'SOLID', color: { r: 0, g: 0, b: 0 } }, 'color', variable,
  );
  node.fills = [paint];
}

/** Bind a node's stroke to a colour variable. */
function strokeVar(node, variable, weight) {
  if (!variable) { warn('strokeVar called without a variable'); return; }
  const paint = figma.variables.setBoundVariableForPaint(
    { type: 'SOLID', color: { r: 0, g: 0, b: 0 } }, 'color', variable,
  );
  node.strokes = [paint];
  node.strokeWeight = weight === undefined ? 1 : weight;
  node.strokeAlign = 'INSIDE';
}

/** Bind a numeric field, tolerating fields a given node type rejects. */
function bindNum(node, field, variable) {
  if (!variable) return;
  try { node.setBoundVariable(field, variable); }
  catch (e) { warn(`could not bind ${field} on ${node.type}: ${e.message}`); }
}

function bindRadius(node, variable) {
  for (const corner of ['topLeftRadius', 'topRightRadius', 'bottomLeftRadius', 'bottomRightRadius']) {
    bindNum(node, corner, variable);
  }
}

function bindPadding(node, variable) {
  for (const side of ['paddingLeft', 'paddingRight', 'paddingTop', 'paddingBottom']) {
    bindNum(node, side, variable);
  }
}

// ----------------------------------------------------------------- nodes ----
/**
 * Auto-layout frame. Everything structural in this file is built with one,
 * so content changes reflow instead of colliding.
 */
function AL(name, direction, opts) {
  const o = opts || {};
  const f = figma.createFrame();
  f.name = name;
  f.layoutMode = direction;
  f.primaryAxisSizingMode = o.primary || 'AUTO';
  f.counterAxisSizingMode = o.counter || 'AUTO';
  f.itemSpacing = o.gap === undefined ? 0 : o.gap;
  f.paddingLeft = o.px === undefined ? (o.p || 0) : o.px;
  f.paddingRight = o.px === undefined ? (o.p || 0) : o.px;
  f.paddingTop = o.py === undefined ? (o.p || 0) : o.py;
  f.paddingBottom = o.py === undefined ? (o.p || 0) : o.py;
  if (o.align) { try { f.counterAxisAlignItems = o.align; } catch (e) { warn('align ' + o.align + ' rejected on ' + name + ': ' + e.message); } }
  if (o.justify) {
    // SPACE_BETWEEN needs a fixed primary axis in some Figma versions; a
    // rejection here should degrade the alignment, not abort the whole build.
    try { f.primaryAxisAlignItems = o.justify; }
    catch (e) { warn('justify ' + o.justify + ' rejected on ' + name + ': ' + e.message); }
  }
  if (o.wrap) {
    try {
      f.layoutWrap = 'WRAP';
      if (o.crossGap !== undefined) f.counterAxisSpacing = o.crossGap;
    } catch (e) { warn('wrap rejected on ' + name + ': ' + e.message); }
  }
  f.fills = o.fillVar ? [] : (o.fill ? [solid(o.fill)] : []);
  if (o.fillVar) fillVar(f, o.fillVar);
  if (o.strokeVar) strokeVar(f, o.strokeVar, o.strokeWeight);
  if (o.radiusVar) { f.cornerRadius = 0; bindRadius(f, o.radiusVar); }
  else if (o.radius !== undefined) f.cornerRadius = o.radius;
  if (o.clip !== undefined) f.clipsContent = o.clip;
  return f;
}

/** Plain frame, for decorative blocks that are not containers. */
function BOX(name, w, h, opts) {
  const o = opts || {};
  const f = figma.createFrame();
  f.name = name;
  f.resize(w, h);
  f.fills = [];
  if (o.fill) f.fills = [solid(o.fill)];
  if (o.fillVar) fillVar(f, o.fillVar);
  if (o.strokeVar) strokeVar(f, o.strokeVar, o.strokeWeight);
  if (o.radiusVar) { f.cornerRadius = 0; bindRadius(f, o.radiusVar); }
  else if (o.radius !== undefined) f.cornerRadius = o.radius;
  if (o.clip !== undefined) f.clipsContent = o.clip;
  return f;
}

/**
 * Text node. Fonts must already be loaded — see loadAllFonts().
 * `style` is a text style id; `colorVar` binds the fill to a variable.
 */
function TXT(name, characters, style, colorVar, opts) {
  const o = opts || {};
  const t = figma.createText();
  t.name = name || characters.slice(0, 32);
  t.fontName = o.font || { family: 'Inter', style: 'Regular' };
  t.characters = characters;
  if (style) { try { t.setTextStyleIdAsync ? null : null; } catch (e) { /* set below */ } }
  if (colorVar) fillVar(t, colorVar);
  if (o.size) t.fontSize = o.size;
  if (o.lh) t.lineHeight = { unit: 'PERCENT', value: o.lh };
  if (o.ls !== undefined) t.letterSpacing = { unit: 'PERCENT', value: o.ls };
  if (o.case) t.textCase = o.case;
  if (o.align) t.textAlignHorizontal = o.align;
  if (o.width) {
    // Fixed width + HEIGHT auto-resize is the only combination that wraps
    // reliably; the default WIDTH_AND_HEIGHT ignores FILL and collapses.
    t.textAutoResize = 'HEIGHT';
    t.resize(o.width, t.height);
  } else {
    t.textAutoResize = 'WIDTH_AND_HEIGHT';
  }
  return t;
}

/** Append children and return the parent, so builders read top-down. */
function add(parent, children) {
  for (const c of children) if (c) parent.appendChild(c);
  return parent;
}

/** Make a child stretch along its parent's counter axis. */
function fill(node) {
  try { node.layoutSizingHorizontal = 'FILL'; }
  catch (e) { warn(`FILL rejected on ${node.name}: ${e.message}`); }
  return node;
}

/** Position a top-level frame on the page. */
function place(node, x, y) { node.x = x; node.y = y; return node; }
