/**
 * Bundles the Figma plugin.
 *
 * Concatenates figma-plugin/src/*.js in filename order and prepends the site's
 * real content as a DATA constant, so the plugin builds the Figma file from
 * the same source as the website.
 *
 * Run: npm run figma:plugin
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const pluginDir = resolve(root, 'figma-plugin');
const srcDir = resolve(pluginDir, 'src');
const tmp = resolve(pluginDir, '.content.mjs');

execFileSync(
  resolve(root, 'node_modules/.bin/esbuild'),
  [
    resolve(root, 'scripts/figma/_content-entry.ts'),
    '--bundle', '--format=esm', '--platform=node',
    '--define:import.meta.env.PUBLIC_CONTACT_ENDPOINT=""',
    '--define:import.meta.env.PUBLIC_CONTACT_ACCESS_KEY=""',
    '--define:import.meta.env.BASE_URL="/"',
    `--outfile=${tmp}`,
  ],
  { stdio: ['ignore', 'ignore', 'inherit'] },
);

const content = await import(pathToFileURL(tmp).href);
// Project the content down to the fields the plugin actually renders. The
// full case studies are ~340 KB of prose the plugin never reads.
const project = (p) => ({
  slug: p.slug, title: p.title, tagline: p.tagline, description: p.description,
  industry: p.industry, year: p.year, status: p.status, projectType: p.projectType,
  role: p.role, team: p.team, timeline: p.timeline, contribution: p.contribution,
  tags: p.tags, cover: { tint: p.cover.tint, alt: p.cover.alt },
  overview: p.overview
    ? {
        narrative: p.overview.narrative,
        narrativeExtra: p.overview.narrativeExtra,
        highlights: p.overview.highlights || [],
      }
    : null,
  insights: (p.insights || []).slice(0, 4).map((i) => ({
    title: i.title, detail: i.detail, quote: i.quote, evidence: i.evidence,
  })),
});

const DATA = {
  profile: JSON.parse(JSON.stringify(content.profile)),
  navigation: JSON.parse(JSON.stringify(content.navigation)),
  allProjects: content.allProjects.map(project),
  featuredProjects: content.featuredProjects.map(project),
  industriesCovered: content.industriesCovered,
  industryFacets: content.industryFacets(),
};
rmSync(tmp, { force: true });

const files = readdirSync(srcDir).filter((f) => f.endsWith('.js')).sort();
const parts = files.map((f) => `// ---- src/${f} ${'-'.repeat(Math.max(0, 60 - f.length))}\n${readFileSync(resolve(srcDir, f), 'utf8')}`);

const out = `/* eslint-disable */
// GENERATED by scripts/figma/build-plugin.mjs — do not edit.
// Source: figma-plugin/src/*.js  +  the site's own content.
// Rebuild with: npm run figma:plugin

const DATA = ${JSON.stringify(DATA, null, 2)};

${parts.join('\n\n')}
`;

writeFileSync(resolve(pluginDir, 'code.js'), out, 'utf8');

const kb = (Buffer.byteLength(out) / 1024).toFixed(0);
console.log(`✓ figma-plugin/code.js  (${files.length} sources + content, ${kb} KB)`);
console.log(`  projects: ${DATA.allProjects.length}  ·  facets: ${DATA.industryFacets.length}`);
