/**
 * ===========================================================================
 * SITE CONFIGURATION — single source of truth for identity, SEO and contact.
 *
 * ⚠️  EDIT ME FIRST: the three `profile.social` URLs and `profile.phone` are
 *     best guesses. Replace them with your real handles before you publish.
 * ===========================================================================
 */

export interface SocialLink {
  label: string;
  handle: string;
  href: string;
  /** Rendered in the footer + contact section */
  primary?: boolean;
}

export const profile = {
  name: 'Nasa Sri Sai V.B',
  shortName: 'Sri Sai',
  initials: 'NS',
  role: 'UX/UI Designer · Product Designer',
  roleLong: 'UX/UI Designer | Product Designer | Digital Experience Designer',
  location: 'India · Working with teams worldwide',
  timezone: 'IST (UTC+5:30)',
  availability: 'Open to product design roles & selected freelance work',
  email: 'nasasrisaivb@gmail.com',

  /** Headline value proposition — used in the hero and as the OG description. */
  proposition:
    'I design digital products that turn complex problems into simple, useful experiences.',

  /** One-paragraph elevator pitch — used on About, resume and structured data. */
  summary:
    'I am a UX/UI and product designer working end to end: research and strategy through information architecture, interaction and interface design, into design systems and shipped product. I have designed multi-sided marketplaces, logistics operations tooling, healthcare and diagnostic platforms, and SaaS dashboards — the kind of products where the hard part is not how a screen looks, but how much complexity you can take away from the person using it.',

  social: [
    {
      label: 'LinkedIn',
      handle: 'in/nasasrisaivb',
      // TODO: replace with your real LinkedIn URL
      href: 'https://www.linkedin.com/in/nasasrisaivb/',
      primary: true,
    },
    {
      label: 'Behance',
      handle: 'nasasrisaivb',
      // TODO: replace with your real Behance URL
      href: 'https://www.behance.net/nasasrisaivb',
      primary: true,
    },
    {
      label: 'GitHub',
      handle: 'nasasrisaivb-afk',
      href: 'https://github.com/nasasrisaivb-afk',
      primary: true,
    },
  ] satisfies SocialLink[],

  /** Shown on the resume + contact card. */
  resume: {
    file: '/resume/Nasa-Sri-Sai-VB-Resume.pdf',
    fileName: 'Nasa-Sri-Sai-VB-Resume.pdf',
    updated: 'September 2026',
  },
} as const;

export const site = {
  title: `${profile.name} — ${profile.role}`,
  shortTitle: `${profile.name}`,
  description:
    'Portfolio of Nasa Sri Sai V.B, a UX/UI and product designer working across healthcare, logistics, agriculture, SaaS, fintech and e-commerce — from user research and strategy to interface design, design systems and shipped product.',
  keywords: [
    'UX Designer',
    'UI Designer',
    'Product Designer',
    'UX/UI Designer',
    'Digital Product Designer',
    'Design Systems',
    'Healthcare UX',
    'Logistics UX',
    'Agriculture UX',
    'SaaS product design',
    'Accessibility WCAG',
  ],
  locale: 'en_IN',
  lang: 'en',
  /** Default social sharing image (1200×630), generated by `npm run og`. */
  ogImage: '/og/og-default.png',
  themeColorLight: '#f7f5f0',
  themeColorDark: '#12110e',
} as const;

/** Primary navigation. Sections live on the home page; pages have real URLs. */
export const navigation = [
  { label: 'Home', href: '/', section: 'top' },
  { label: 'Work', href: '/#work', section: 'work' },
  { label: 'About', href: '/#about', section: 'about' },
  { label: 'Process', href: '/#process', section: 'process' },
  { label: 'Resume', href: '/#resume', section: 'resume' },
  { label: 'Contact', href: '/#contact', section: 'contact' },
] as const;

/** Secondary links grouped in the footer. */
export const footerLinks = [
  {
    heading: 'Portfolio',
    links: [
      { label: 'Selected work', href: '/work' },
      { label: 'Design process', href: '/#process' },
      { label: 'About me', href: '/#about' },
      { label: 'Resume', href: '/resume' },
    ],
  },
  {
    heading: 'Get in touch',
    links: [
      { label: 'Contact form', href: '/#contact' },
      { label: profile.email, href: `mailto:${profile.email}` },
      ...profile.social.map((s) => ({ label: s.label, href: s.href })),
    ],
  },
] as const;

/**
 * Contact form delivery.
 * Set PUBLIC_CONTACT_ENDPOINT in `.env` to POST submissions to a real service.
 * With no endpoint the form still works — it validates and hands the composed
 * message to the visitor's mail client (see ContactForm.astro).
 */
export const contactConfig = {
  endpoint: import.meta.env.PUBLIC_CONTACT_ENDPOINT ?? '',
  accessKey: import.meta.env.PUBLIC_CONTACT_ACCESS_KEY ?? '',
  subjectPrefix: 'Portfolio enquiry',
} as const;
